Update GH actions

diff --git a/.github/workflows/Render-README.yaml b/.github/workflows/Render-README.yaml
--- a/.github/workflows/Render-README.yaml
+++ b/.github/workflows/Render-README.yaml
@@ -1,41 +1,38 @@
+# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
+# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
+
 on:
   push:
-    branches:
-      - main
-      - development
-    paths:
-      - README.Rmd
+    paths: ['README.Rmd']
 
 name: Render-README
 
 jobs:
   render-readme:
-    # The type of runner that the job will run on
-    runs-on: macOS-latest
-
-    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+    runs-on: ubuntu-latest
+    env:
+      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
     steps:
-    - uses: actions/checkout@v2
-    - uses: r-lib/actions/setup-r@v1
-    - uses: r-lib/actions/setup-pandoc@v1
+      - name: Checkout repo
+        uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
 
-    # Install packages needed
-    - name: install required packages
-      run: |
-          install.packages("remotes")
-          remotes::install_local(".")
-          remotes::install_cran("rmarkdown")
-      shell: Rscript {0}
+      - uses: r-lib/actions/setup-pandoc@v1
 
-    # Render READEME.md using rmarkdown
-    - name: render README
-      run: Rscript -e 'rmarkdown::render("README.Rmd")'
+      - uses: r-lib/actions/setup-r@v1
 
-    # Commit and push files to github
-    - name: commit rendered README
-      run: |
-        git config --local user.email "actions@github.com"
-        git config --local user.name "GitHub Actions"
-        git add README.md man/figures/README-*
-        git commit -m "Re-build README.md" || echo "No changes to commit"
-        git push origin || echo "No changes to commit"
+      - uses: r-lib/actions/setup-r-dependencies@v1
+        with:
+          extra-packages: rmarkdown
+
+      - name: Render README files
+        run: Rscript -e 'rmarkdown::render("README.Rmd")'
+
+      - name: Commit README
+        run: |
+          git config --local user.email "actions@github.com"
+          git config --local user.name "GitHub Actions"
+          git add README.md
+          git commit -m "Re-build README.md" || echo "No changes to commit"
+          git push origin || echo "No changes to commit"
